### ISSUE TITLE
How do I pass Model into landingPageBody 

### ISSUE THREAD

**Issue by TheBitmonkey** [dillonkearns/elm-pages-tailwind-starter#1]
Hi Dillon,

I am an Elm beginner and am having difficulties passing Model into landingPageBody

landingPageBody : List (Html Msg)
landingPageBody model =

This fails because it's not the structure.
changing the first line to this...

landingPageBody : Model -> List (Html Msg)

Makes the Compiler moan about the view wanting just the List.

Any help would be appreciated.

**Comment by dillonkearns** [comment]
Hello! I'd love to help you get up and running. It's a little easier to answer questions in real-time, would you mind asking this question in the `#elm-pages` channel in [the Elm Slack](https://elmlang.herokuapp.com/)?
